[versions]
springFramework = "6.2.2"
springCloud = "2025.0.1"
junit = "6.0.2"
assertj = "3.27.7"
reactor = "3.8.2"
nimbusJoseJwt = "10.7"
groovy = "5.0.4"
googleJavaFormat = "1.33.0"

[libraries]
spring-framework-bom = { group = "org.springframework", name = "spring-framework-bom", version.ref = "springFramework" }
spring-cloud-bom = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref = "springCloud" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
reactor-test = { group = "io.projectreactor", name = "reactor-test", version.ref = "reactor" }
nimbus-jose-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbusJoseJwt" }
apache-groovy = { group = "org.apache.groovy", name = "groovy", version.ref = "groovy" }

[plugins]
spring-deps-management = { id = "io.spring.dependency-management", version = "1.1.7" }
spotless = { id = "com.diffplug.spotless", version = "8.2.1" }